---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: BlueWalk
description: This is my personal OS image.
base-image: quay.io/fedora-ostree-desktops/base-atomic
image-version: latest

modules:
  - type: containerfile
    snippets:
      - COPY --from=ghcr.io/ublue-os/akmods:main-42 /rpms /tmp/rpms
      - COPY --from=ghcr.io/ublue-os/akmods:main-42 /kernel-rpms /tmp/rpms/kernel
      - RUN find /tmp/rpms
      - RUN rpm -q ublue-os-akmods-addons || rpm-ostree install /tmp/rpms/ublue-os/ublue-os-akmods-addons*.rpm

  - type: files
    files:
      - source: system
        destination: /
      - source: system/usr
        destination: /usr
      - source: system/etc
        destination: /etc
      - source: waydroid-setup.sh
        destination: /usr/bin/waydroid-setup
        mode: 0755
      - source: waydroid.desktop
        destination: /usr/share/applications/waydroid.desktop
      - source: waydroid-session.desktop
        destination: /usr/share/wayland-sessions/waydroid.desktop
      - source: niri.desktop
        destination: /usr/share/wayland-sessions/niri.desktop
      - source: waydroid.service
        destination: /etc/skel/.config/systemd/user/waydroid.service
      - source: setup-waydroid
        destination: /usr/libexec/ublue-os/ujust/setup-waydroid
        mode: 0755

  - type: rpm-ostree
    install:
      - just
      - powerstat

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/ublue-os/packages/repo/fedora-%OS_VERSION%/ublue-os-packages-fedora-%OS_VERSION%.repo
    install:
      - ublue-os-udev-rules
      - ublue-os-update-services
      - ublue-os-signing
      - ublue-os-luks
      - ublue-os-just

  - type: rpm-ostree
    optfix:
      - zen
    repos:
      - https://repo.secureblue.dev/secureblue.repo
      - https://copr.fedorainfracloud.org/coprs/yalter/niri/repo/fedora-%OS_VERSION%/yalter-niri-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ulysg/xwayland-satellite/repo/fedora-%OS_VERSION%/ulysg-xwayland-satellite-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/errornointernet/quickshell/repo/fedora-%OS_VERSION%/errornointernet-quickshell-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/sneexy/zen-browser/repo/fedora-%OS_VERSION%/sneexy-zen-browser-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/secureblue/trivalent/repo/fedora-%OS_VERSION%/secureblue-trivalent-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/scottames/ghostty/repo/fedora-%OS_VERSION%/scottames-ghostty-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/wef/cliphist/repo/fedora-%OS_VERSION%/wef-cliphist-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/heus-sueh/packages/repo/fedora-%OS_VERSION%/heus-sueh-packages-fedora-%OS_VERSION%.repo
    install:
      - niri
      - xdg-desktop-portal-gtk
      - xdg-desktop-portal-gnome
      - gnome-keyring
      - xwayland-satellite
      - xsettingsd
      - quickshell-git
      - brightnessctl
      - jetbrains-mono-fonts
      - fira-code-fonts
      - qt5ct
      - qt6ct
      - cliphist
      - fzf
      - matugen
      - gammastep
      - wl-clipboard
      - micro
      - starship
      - zen-browser
      - ghostty
      - distrobox
      - greetd
      - tuigreet
      - greetd-selinux
      - waydroid
      - trivalent
      - trivalent-subresource-filter
      - just
      - vim
      - neovim
      - python3-neovim
      - openssl
      - pavucontrol
      - wireplumber
      - pipewire
      - pamixer
      - pulseaudio-utils
      - dbus-tools
      - xdg-user-dirs
      - dbus-daemon
      - vulkan-validation-layers
      - vulkan-tools
      - xfce-polkit
      - fprintd-pam
      - network-manager-applet
      - NetworkManager-openvpn
      - NetworkManager-openvpn-gnome
      - NetworkManager-openconnect
      - NetworkManager-openconnect-gnome
      - bluez
      - bluez-tools
      - blueman
      - firewall-config
    remove:
      - firefox
      - firefox-langpacks
      - alacritty

  - type: rpm-ostree
    install:
      - heif-pixbuf-loader
      - ffmpeg
      - ffmpeg-libs
      - ffmpegthumbnailer
      - pipewire-libs-extra
      - libfdk-aac
      - gstreamer1-plugins-ugly
    remove:
      - gstreamer1-plugins-ugly-free
      - fdk-aac-free
      - ffmpeg-free
      - libavcodec-free
      - libavdevice-free
      - libavfilter-free
      - libavformat-free
      - libavutil-free
      - libpostproc-free
      - libswresample-free
      - libswscale-free

  - type: systemd
    system:
      enabled:
        - greetd-boot.service
        - greetd.service
        - xwayland-satellite.service

  - type: script
    scripts:
      - installsignedkernel.sh
      - installandroidudev.sh
      - ensureautoupdates.sh
      - fixupstreamicdloaderbug.sh
      - installproprietarypackages.sh
      - installrpmfusion.sh
      - installanydesk.sh
      - removeunusedrepos.sh
      - regenerateinitramfs.sh
      - configure-system.sh

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - org.gnome.Loupe
      - scope: user

  - type: signing
