---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: BlueWalk
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main:latest
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  - type: dnf
    repos:
      copr:
        - yalter/niri
        - errornointernet/quickshell
        - atim/starship
        - sneexy/zen-browser
        - scottames/ghostty
        - wef/cliphist
        - heus-sueh/packages
        - content: |
          [anydesk]
          name=AnyDesk Fedora - stable
          baseurl=http://rpm.anydesk.com/fedora/$basearch/
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://keys.anydesk.com/repos/RPM-GPG-KEY
        target: /etc/yum.repos.d/AnyDesk-Fedora.repo
        
    install:
      packages:
        - niri
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-gnome
        - gnome-keyring
        - quickshell-git
        - brightnessctl
        - jetbrains-mono-fonts
        - fira-code-fonts
        - qt5ct
        - qt6ct
        - cliphist
        - matugen
        - gammastep
        - wl-clipboard
        - micro
        - starship
        - zen-browser
        - ghostty
        - anydesk
        - distrobox
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - alacritty

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
