---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
  
name: BlueWalk

description: My personal Fedora-based OSTree image with a custom desktop environment and tools.

base-image: quay.io/fedora-ostree-desktops/base-atomic

image-version: latest

modules:
  - from-file: packages/foundation.yml

  - from-file: shared/niri-modules.yaml

  - from-file: shared/quickshell-modules.yaml

  - from-file: shared/default-flatpaks.yml

  - from-file: shared/systemd.yml

  - from-file: shared/final-modules.yml

