---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: BlueWalk
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main:latest
image-version: latest

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
        
  - type: dnf
    repos:
      copr:
        - yalter/niri
        - ulysg/xwayland-satellite 
        - errornointernet/quickshell
        - atim/starship
        - sneexy/zen-browser
        - scottames/ghostty
        - wef/cliphist
        - heus-sueh/packages
        - content: |
          [anydesk]
          name=AnyDesk Fedora - stable
          baseurl=http://rpm.anydesk.com/fedora/$basearch/
          gpgcheck=1
          repo_gpgcheck=1
          gpgkey=https://keys.anydesk.com/repos/RPM-GPG-KEY
        target: /etc/yum.repos.d/AnyDesk-Fedora.repo
        
    install:
      packages:
        - niri
        - xdg-desktop-portal-gtk
        - xdg-desktop-portal-gnome
        - gnome-keyring
        - xwayland-satellite
        - xsettingsd
        - quickshell-git
        - brightnessctl
        - jetbrains-mono-fonts
        - fira-code-fonts
        - qt5ct
        - qt6ct
        - cliphist
        - fzf
        - matugen
        - gammastep
        - wl-clipboard
        - micro
        - starship
        - zen-browser
        - ghostty
        - anydesk
        - distrobox
        - greetd
        - tuigreet
        - greetd-selinux
        - waydroid
    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
        - alacritty
        
  - type: systemd
      system:
        enabled:
          - greetd-boot.service
          - greetd.service
          - xwayland-satellite.service

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: script
    scripts:
      - |
        #!/bin/bash
        set -eux
        # Install Material Symbols font
        mkdir -p /usr/local/share/fonts
        curl -L "https://github.com/google/material-design-icons/raw/master/variablefont/MaterialSymbolsRounded%5BFILL%2CGRAD%2Copsz%2Cwght%5D.ttf" -o /usr/local/share/fonts/MaterialSymbolsRounded.ttf
       
        # Configure Waydroid: SELinux and initialization
        setsebool -P waydroid_can_use_modules 1
        semanage permissive -a waydroid_t
        waydroid init -s GAPPS -f
        # Install ujust script for Waydroid
        mkdir -p /usr/libexec/ublue-os/ujust
        curl -L "https://raw.githubusercontent.com/ublue-os/bazzite/main/system_files/desktop/usr/libexec/ublue-os/ujust/setup-waydroid" -o /usr/libexec/ublue-os/ujust/setup-waydroid
        chmod +x /usr/libexec/ublue-os/ujust/setup-waydroid
        # Waydroid initialization script
        cat > /usr/bin/waydroid-setup << 'EOF'
        #!/bin/bash
        systemctl --user start waydroid-container
        waydroid session start
        EOF
        chmod +x /usr/bin/waydroid-setup
        # Systemd service for Waydroid
        mkdir -p /etc/skel/.config/systemd/user
        cat > /etc/skel/.config/systemd/user/waydroid.service << 'EOF'
        [Unit]
        Description=Waydroid Session
        After=graphical-session.target
        [Service]
        ExecStart=/usr/bin/waydroid-setup
        Restart=on-failure
        [Install]
        WantedBy=graphical-session.target
        EOF
        # Waydroid launcher
        mkdir -p /usr/share/applications
        cat > /usr/share/applications/waydroid.desktop << 'EOF'
        [Desktop Entry]
        Name=Waydroid
        Exec=waydroid-setup
        Icon=waydroid
        Type=Application
        EOF
        # Wayland session for Waydroid
        mkdir -p /usr/share/wayland-sessions
        cat > /usr/share/wayland-sessions/waydroid.desktop << 'EOF'
        [Desktop Entry]
        Name=Waydroid
        Comment=Android in a container
        Exec=waydroid session start
        Type=Application
        EOF
        # Wayland session for Niri
        mkdir -p /usr/share/wayland-sessions
        cat > /usr/share/wayland-sessions/niri.desktop << 'EOF'
        [Desktop Entry]
        Name=Niri
        Comment=A scrollable-tiling Wayland compositor
        Exec=niri
        Type=Application
        DesktopNames=niri
        EOF
        # Install dgop
        sudo sh -c "curl -L https://github.com/AvengeMedia/dgop/releases/latest/download/dgop-linux-$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/').gz | gunzip | tee /usr/local/bin/dgop > /dev/null && chmod +x /usr/local/bin/dgop"
        # Cleanup
        dnf clean all
        rm -rf /var/cache/dnf /tmp/*
