---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
  
name: bluewalk

description: My personal Fedora-based OSTree image with a custom desktop environment and tools.

base-image: quay.io/fedora-ostree-desktops/base-atomic

image-version: 42

modules:
  - from-file: common/foundation.yml
  - from-file: common/niri-modules.yml
  - from-file: common/quickshell-modules.yml
  - from-file: common/default-flatpaks.yml
  - from-file: common/systemd.yml
  - from-file: common/final-modules.yml
