modules:
  - from-file: packages/foundation.yml

  - from-file: shared/niri-modules.yaml

  - from-file: shared/quickshell-modules.yaml

  - from-file: shared/default-flatpaks.yml

  - from-file: shared/systemd.yml

  - from-file: shared/final-modules.yml
